"""
src/train_libreyolo_task.py

Generic LibreYOLO trainer for any (task, variant) combination, so new
experiments NEVER overwrite previous weights.

Naming contract (deterministic, collision-free between variants):
    weights/<artifact>_<variant>[_<tag>].pt / .onnx
    runs/train_<variant>/<task>[_<tag>]/

Variants — all STRETCH resize, NO letterbox/padding (see src/preprocess_registry.py):
    dfine_nano  -> pretrained LibreDFINEn.pt   imgsz 640  lr0 5e-4
    dfine_small -> pretrained LibreDFINEs.pt   imgsz 640  lr0 3e-4
    picodet_s   -> pretrained LibrePICODETs.pt imgsz 416  lr0 1e-3
    picodet_m   -> pretrained LibrePICODETm.pt imgsz 416  lr0 1e-3

RESOLUTION CONTRACT: imgsz must stay identical across train / ONNX export /
inference (M1_PICODET = 416, M1_DFINE = 640 in src/preprocess_registry.py).

Tasks:
    plate       (Model 1)  -> plate_detector_<variant>.pt
    components  (Model 2)  -> component_detector_<variant>.pt
    charbox     (Model 3A) -> character_box_detector_<variant>.pt
    lao_plate   (Lao M1)   -> plate_detector_lao_<variant>.pt
"""

import shutil
from pathlib import Path

import yaml
from libreyolo import LibreYOLO

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_WEIGHTS_DIR = PROJECT_ROOT / "weights"
RUNS_DIR = PROJECT_ROOT / "runs"

VARIANTS = {
    "dfine_nano":  {"pretrained": "LibreDFINEn.pt",   "imgsz": 640, "lr0": 5e-4},
    "dfine_small": {"pretrained": "LibreDFINEs.pt",   "imgsz": 640, "lr0": 3e-4},
    "picodet_s":   {"pretrained": "LibrePICODETs.pt", "imgsz": 416, "lr0": 1e-3},
    "picodet_m":   {"pretrained": "LibrePICODETm.pt", "imgsz": 416, "lr0": 1e-3},
}

PLATE_DATA_YAML = PROJECT_ROOT / "datasets" / "Thai" / "LPR_2_BBox" / "data.yaml"

TASKS = {
    "plate": {
        "artifact": "plate_detector",
        "dataset_dir": PLATE_DATA_YAML.parent,
        "yaml_name": "data.yaml",  # generated by prepare_bbox_dataset
        "nc": 1,
        "names": ["plate"],
    },
    "components": {
        "artifact": "component_detector",
        "dataset_dir": PROJECT_ROOT / "datasets" / "Thai" / "LPR 2 - Charactor Detection.yolov11",
        "yaml_name": "dfine_data.yaml",
        "nc": 2,
        "names": ["plate_char", "province"],
    },
    "charbox": {
        "artifact": "character_box_detector",
        "dataset_dir": PROJECT_ROOT / "datasets" / "Thai" / "LPR 2 - Character Box Detection.yolov11",
        "yaml_name": "dfine_data.yaml",
        "nc": 1,
        "names": ["char"],
    },
    "lao_plate": {
        "artifact": "plate_detector_lao",
        "dataset_dir": PROJECT_ROOT / "datasets" / "Lao" / "laos plate.v3i.yolov11",
        "yaml_name": "dfine_data.yaml",
        "nc": 2,
        "names": ["0", "plate"],
    },
}


def ensure_plate_dataset():
    if not PLATE_DATA_YAML.exists():
        from prepare_bbox_dataset import convert_polygon_to_bbox
        convert_polygon_to_bbox()


def ensure_clean_yaml(task):
    """Write a data.yaml with absolute paths (LibreYOLO requirement)."""
    cfg = TASKS[task]
    yaml_path = cfg["dataset_dir"] / cfg["yaml_name"]
    if yaml_path.exists() and cfg["yaml_name"] == "data.yaml":
        return yaml_path  # dataset yaml already exists with absolute paths
    data = {
        "train": str((cfg["dataset_dir"] / "train" / "images").resolve()),
        "val":   str((cfg["dataset_dir"] / "valid" / "images").resolve()),
        "test":  str((cfg["dataset_dir"] / "test" / "images").resolve()),
        "nc":    cfg["nc"],
        "names": cfg["names"],
    }
    with open(yaml_path, "w", encoding="utf-8") as f:
        yaml.dump(data, f, sort_keys=False)
    return yaml_path


def target_paths(task, variant, tag=""):
    """Deterministic output paths for a (task, variant, tag) combination."""
    cfg = TASKS[task]
    tag_str = f"_{tag.strip().lstrip('_')}" if tag.strip() else ""
    stem = f"{cfg['artifact']}_{variant}{tag_str}"
    return {
        "pt": OUTPUT_WEIGHTS_DIR / f"{stem}.pt",
        "onnx": OUTPUT_WEIGHTS_DIR / f"{stem}.onnx",
        "run_dir": RUNS_DIR / f"train_{variant}" / f"{task}{tag_str}",
    }


def train_libreyolo_task(task, variant, epochs=30, batch=8, imgsz=None,
                         patience=12, device="mps", export_onnx=True, tag="",
                         overwrite=False):
    """Train one (task, variant). Returns True if trained, False if skipped.

    Old weights are preserved: if the target .pt already exists and neither
    a tag nor overwrite=True was given, the task is SKIPPED with guidance.
    """
    if task not in TASKS:
        raise KeyError(f"Unknown task '{task}'. Valid: {list(TASKS.keys())}")
    if variant not in VARIANTS:
        raise KeyError(f"Unknown variant '{variant}'. Valid: {list(VARIANTS.keys())}")

    spec = VARIANTS[variant]
    paths = target_paths(task, variant, tag)

    if paths["pt"].exists() and not overwrite:
        print("\n" + "=" * 70)
        print(f"⏭️  SKIP — target already exists (old model preserved):")
        print(f"   {paths['pt'].name}")
        print(f"   → เทรนเวอร์ชันใหม่ไม่ทับของเดิม : เพิ่ม --tag <ชื่อ>  (เช่น --tag v2)")
        print(f"   → บังคับแทนที่ของเดิม           : เพิ่ม --overwrite")
        print("=" * 70)
        return False

    if imgsz is None:
        imgsz = spec["imgsz"]

    pretrained = OUTPUT_WEIGHTS_DIR / spec["pretrained"]
    if not pretrained.exists():
        raise FileNotFoundError(f"Pretrained weights not found: {pretrained}")

    if task == "plate":
        ensure_plate_dataset()
    data_yaml = ensure_clean_yaml(task)
    run_dir = paths["run_dir"]
    run_dir.mkdir(parents=True, exist_ok=True)
    OUTPUT_WEIGHTS_DIR.mkdir(parents=True, exist_ok=True)

    print("\n" + "=" * 70)
    print(f"🚀 LibreYOLO Training — {task} × {variant}" + (f" (tag: {tag})" if tag else ""))
    print(f"   Pretrained: {pretrained.name}")
    print(f"   Dataset   : {TASKS[task]['dataset_dir'].name}")
    print(f"   Output    : {paths['pt'].name}")
    print(f"   Epochs    : {epochs} | Batch: {batch} | Imgsz: {imgsz} | Patience: {patience}")
    print(f"   ⚠️ RESOLUTION CONTRACT: imgsz={imgsz} must stay the same at ONNX")
    print(f"      export AND inference (stretch resize, no letterbox/padding).")
    print("=" * 70)

    model = LibreYOLO(str(pretrained))
    model.train(
        data=str(data_yaml),
        epochs=epochs,
        batch=batch,
        imgsz=imgsz,
        lr0=spec["lr0"],
        patience=patience,
        device=device,
        project=str(run_dir.parent),
        name=run_dir.name,
        exist_ok=True,
    )

    best_pt = run_dir / "weights" / "best.pt"
    if not best_pt.exists():
        candidates = list(run_dir.glob("**/*.pt")) + list(run_dir.glob("**/*.pth"))
        if candidates:
            best_pt = candidates[0]

    if best_pt and best_pt.exists():
        shutil.copy2(best_pt, paths["pt"])
        size_mb = paths["pt"].stat().st_size / 1e6
        print(f"\n✅ Saved best fine-tuned weights → {paths['pt']} ({size_mb:.1f} MB)")

        if export_onnx:
            print(f"Exporting to standalone ONNX (CPU isolated) → {paths['onnx']}...")
            try:
                trained_model = LibreYOLO(str(paths["pt"]), device="cpu")
                trained_model.export(format="onnx", imgsz=imgsz, device="cpu", dynamic=False)
                if hasattr(trained_model, "model_path"):
                    exp_onnx = Path(trained_model.model_path).with_suffix(".onnx")
                    if exp_onnx.exists() and exp_onnx.resolve() != paths["onnx"].resolve():
                        shutil.copy2(exp_onnx, paths["onnx"])
                if paths["onnx"].exists():
                    onnx_mb = paths["onnx"].stat().st_size / 1e6
                    print(f"✅ Exported ONNX → {paths['onnx']} ({onnx_mb:.1f} MB)")
            except Exception as e:
                print(f"⚠️ ONNX export note: {e}")
    else:
        print(f"⚠️ Checkpoint not found in {run_dir}. Check logs.")
        return False

    return True
